### PR TITLE
Merged in I2 project changes

### PR DESCRIPTION
**Pull request by jtgasper3**

### CODE REVIEW

**Comment by jtgasper3** [comment]
@jeffmc930, Can you please give this a quick scan to confirm I didn't blow away any of your customizations?

**Review by jeffmc930 — COMMENTED** [review]
This does walk on some of the changes from the branches: add-new-google-group-settings and additional-subject-address-search. We won't need the modify-group-delete branch any longer. Maybe the best thing to do is remove the changes I've made to your original master, then apply the I2 changes. We can then review the two branches (settings and subject) against it. What do you think?

**Comment by jtgasper3** [comment]
I probably should have confirmed that UCB-master had all of your changes in
it. I'll compare the two branches you mentioned and see what I stomped on.

As I was comparing UCB-master, somehow I flipped to master and was afraid
I'd messed something up. Sigh. It's almost Friday, right? :)

**Comment by jtgasper3** [comment]
So Jeff, is master Unicon original? Can we:
1.  Branch that
2. Apply the newer I2 Grouper changes onto it.
3. Merge those back into master. (Then master would be the i2 baseline)
4. Then re-apply the code from two branches you referenced into a new branch.
5. Then merge those into UCB-master?

Does that sound good?

**Comment by jeffmc930** [comment]
Yes, that makes sense. That’s what I was suggesting. 

Jeff

**Comment by jeffmc930** [comment]
I can also imagine that other folks can utilize the settings changes that we able to get Google to add.

**Comment by jtgasper3** [comment]
Agreed. They probably would. Should be a pretty easy PR to them.

**Comment by jtgasper3** [comment]
@jeffmc930,

> Yes, that makes sense. That’s what I was suggesting.

Great. I was mostly getting confirmation of the steps. I've pushed a the i2 changes into a branch. I'll be sending another PR for you to review/merge... unless you want me to just merge it. It's steps 1-3 from above. Gonna close this guy out.

**Pull request closed without merging**
