### PR TITLE
If the sync attribute is set to no, empty the google group instead of removing it.

### PR DESCRIPTION
**Pull request by jtgasper3**

### CODE REVIEW

**Review by jeffmc930 — APPROVED** [review]
These changes look good. What are you doing for group deletes. Are they being passed through if sync attribute is set to no?

**Comment by jtgasper3** [comment]
Hi Jeff,

I've been pondering on that. By the time the CLC executes the group, along with attributes and  values will all be removed, so I can look into working the PITAttributeAssignValue class to so if I can get it recreated, or maybe just using PITAttributeAssign is enough if it was yes or no it means it was synced at some point and needs to be deleted.

Or, can we just remove the `!connector.shouldSyncGroup(grouperGroup)` check in the `processGroupDelete`method  and let `connector.deleteGooGroup(grouperGroup);`execute and remove the group if it ever existed. The only downside I could see would be that if a group in Grouper matched a non-associated group in Google, then we'd wrongly kill the Google group. But that all depends upon how Google and Grouper are being used together. If all groups in Google are managed by Grouper, or the Google groups managed by Grouper are appropriately namespaced then their shouldn't be a problem.

Thoughts?

**Comment by jeffmc930** [comment]
We are safe to remove the group. Grouper will be managing the groups in the group.b.e namespace within Google. The safer think to do is probably looking at the PIT tables, but we can assume for our purposes we can assume that if the group exists in the groups namespace, we can delete it. My conservative side wants to do the check in PIT tables. In terms of programming effort, is it a wash or a lot more effort. I also wonder if it is a feature that might be used by other schools if we used the PIT tables?

Thoughts?

**Comment by jtgasper3** [comment]
My honest thoughts are: It really needs to be overhauled. This was the first code I ever wrote for Grouper and the first code I ever wrote against Google APIs. There is a lot of technical debt. The user of an attributeDef vs an attributeDefName was probably a big short coming, but I (and David Langenberg) didn't know any better at the time. I could keep going on things I don't like but...

PIT is probably the best way if one was doing a major overhaul, but a prereq would be switching the shouldSyncGroup from a boolean to a enum because we now have, `true`, `false`, and the newly added `sometimes` for when we want to keep part of it around.

We could certainly do it, but I think it would take quite a bit of testing, etc to make sure we didn't poke one place and pop out another. If the goal is as a direct change (pull request) for the Grouper project, we'd probably want to open a dialog as this might be a big enough change that others would want to be cautious of and would need to commit to testing because everyone is doing things differently and using different parts of the provisioner functionality.

Just my thoughts.

**Comment by jeffmc930** [comment]
Okay. It sounds like going with “send delete to every system. If it has the group, it should delete it” is what we will need to do for now. I totally under the desire for a complete overhaul when we’ve learned more. :)

**Comment by jtgasper3** [comment]
Well, for Google Provisioner it makes sense to send the delete to Google in all cases. I think the AD/LDAP provisioner also does it regardless of attribute settings. I'll confirm.

I've just made the Google Provisioner code changes and will have the changed pushed once I do a quick sanity test.

**Comment by jtgasper3** [comment]
OK, the last change is pushed. I'll go ahead and merge.

**Pull request merged**
